<?php
/**
 * DeleteHistoricDecisionInstancesDto
 *
 * PHP version 5
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/nik54rus/camunda-open-api.git
 * Camunda Codegen version: 3.0.56
 */


namespace Camunda\Client\Model;

use \ArrayAccess;
use \Camunda\Client\ObjectSerializer;

/**
 * DeleteHistoricDecisionInstancesDto Class Doc Comment
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */
class DeleteHistoricDecisionInstancesDto implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $CamundaModelName = 'DeleteHistoricDecisionInstancesDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $CamundaTypes = [
        'historic_decision_instance_ids' => 'string[]',
        'historic_decision_instance_query' => '\Camunda\Client\Model\HistoricDecisionInstanceQueryDto',
        'delete_reason' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $CamundaFormats = [
        'historic_decision_instance_ids' => null,
        'historic_decision_instance_query' => null,
        'delete_reason' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function CamundaTypes()
    {
        return self::$CamundaTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function CamundaFormats()
    {
        return self::$CamundaFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'historic_decision_instance_ids' => 'historicDecisionInstanceIds',
        'historic_decision_instance_query' => 'historicDecisionInstanceQuery',
        'delete_reason' => 'deleteReason'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'historic_decision_instance_ids' => 'setHistoricDecisionInstanceIds',
        'historic_decision_instance_query' => 'setHistoricDecisionInstanceQuery',
        'delete_reason' => 'setDeleteReason'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'historic_decision_instance_ids' => 'getHistoricDecisionInstanceIds',
        'historic_decision_instance_query' => 'getHistoricDecisionInstanceQuery',
        'delete_reason' => 'getDeleteReason'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$CamundaModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['historic_decision_instance_ids'] = isset($data['historic_decision_instance_ids']) ? $data['historic_decision_instance_ids'] : null;
        $this->container['historic_decision_instance_query'] = isset($data['historic_decision_instance_query']) ? $data['historic_decision_instance_query'] : null;
        $this->container['delete_reason'] = isset($data['delete_reason']) ? $data['delete_reason'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets historic_decision_instance_ids
     *
     * @return string[]
     */
    public function getHistoricDecisionInstanceIds()
    {
        return $this->container['historic_decision_instance_ids'];
    }

    /**
     * Sets historic_decision_instance_ids
     *
     * @param string[] $historic_decision_instance_ids A list of historic decision instance ids to delete.
     *
     * @return $this
     */
    public function setHistoricDecisionInstanceIds($historic_decision_instance_ids)
    {
        $this->container['historic_decision_instance_ids'] = $historic_decision_instance_ids;

        return $this;
    }

    /**
     * Gets historic_decision_instance_query
     *
     * @return \Camunda\Client\Model\HistoricDecisionInstanceQueryDto
     */
    public function getHistoricDecisionInstanceQuery()
    {
        return $this->container['historic_decision_instance_query'];
    }

    /**
     * Sets historic_decision_instance_query
     *
     * @param \Camunda\Client\Model\HistoricDecisionInstanceQueryDto $historic_decision_instance_query historic_decision_instance_query
     *
     * @return $this
     */
    public function setHistoricDecisionInstanceQuery($historic_decision_instance_query)
    {
        $this->container['historic_decision_instance_query'] = $historic_decision_instance_query;

        return $this;
    }

    /**
     * Gets delete_reason
     *
     * @return string
     */
    public function getDeleteReason()
    {
        return $this->container['delete_reason'];
    }

    /**
     * Sets delete_reason
     *
     * @param string $delete_reason A string with delete reason.
     *
     * @return $this
     */
    public function setDeleteReason($delete_reason)
    {
        $this->container['delete_reason'] = $delete_reason;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
