<?php
/**
 * CleanableHistoricBatchReportResultDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * CleanableHistoricBatchReportResultDtoTest Class Doc Comment
 *
 * @category    Class
 * @description CleanableHistoricBatchReportResultDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CleanableHistoricBatchReportResultDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CleanableHistoricBatchReportResultDto"
     */
    public function testCleanableHistoricBatchReportResultDto()
    {
    }

    /**
     * Test attribute "batch_type"
     */
    public function testPropertyBatchType()
    {
    }

    /**
     * Test attribute "history_time_to_live"
     */
    public function testPropertyHistoryTimeToLive()
    {
    }

    /**
     * Test attribute "finished_batches_count"
     */
    public function testPropertyFinishedBatchesCount()
    {
    }

    /**
     * Test attribute "cleanable_batches_count"
     */
    public function testPropertyCleanableBatchesCount()
    {
    }
}
