<?php
/**
 * DeleteProcessInstancesDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * DeleteProcessInstancesDtoTest Class Doc Comment
 *
 * @category    Class
 * @description DeleteProcessInstancesDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DeleteProcessInstancesDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DeleteProcessInstancesDto"
     */
    public function testDeleteProcessInstancesDto()
    {
    }

    /**
     * Test attribute "process_instance_ids"
     */
    public function testPropertyProcessInstanceIds()
    {
    }

    /**
     * Test attribute "delete_reason"
     */
    public function testPropertyDeleteReason()
    {
    }

    /**
     * Test attribute "skip_custom_listeners"
     */
    public function testPropertySkipCustomListeners()
    {
    }

    /**
     * Test attribute "skip_subprocesses"
     */
    public function testPropertySkipSubprocesses()
    {
    }

    /**
     * Test attribute "skip_io_mappings"
     */
    public function testPropertySkipIoMappings()
    {
    }

    /**
     * Test attribute "process_instance_query"
     */
    public function testPropertyProcessInstanceQuery()
    {
    }

    /**
     * Test attribute "historic_process_instance_query"
     */
    public function testPropertyHistoricProcessInstanceQuery()
    {
    }
}
