<?php
/**
 * HistoricVariableInstanceQueryDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/nik54rus/camunda-open-api.git
 * Camunda Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the Camunda code generator program.
 * https://github.com/nik54rus/camunda-open-api
 * Please update the test case below to test the model.
 */

namespace Camunda\Client;

use PHPUnit\Framework\TestCase;

/**
 * HistoricVariableInstanceQueryDtoTest Class Doc Comment
 *
 * @category    Class
 * @description A Historic Variable Instance instance query which defines a list of Historic Variable Instance instances
 * @package     Camunda\Client
 * @author      Camunda Codegen team
 * @link        https://github.com/nik54rus/camunda-open-api
 */
class HistoricVariableInstanceQueryDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HistoricVariableInstanceQueryDto"
     */
    public function testHistoricVariableInstanceQueryDto()
    {
    }

    /**
     * Test attribute "variable_name"
     */
    public function testPropertyVariableName()
    {
    }

    /**
     * Test attribute "variable_name_like"
     */
    public function testPropertyVariableNameLike()
    {
    }

    /**
     * Test attribute "variable_value"
     */
    public function testPropertyVariableValue()
    {
    }

    /**
     * Test attribute "variable_names_ignore_case"
     */
    public function testPropertyVariableNamesIgnoreCase()
    {
    }

    /**
     * Test attribute "variable_values_ignore_case"
     */
    public function testPropertyVariableValuesIgnoreCase()
    {
    }

    /**
     * Test attribute "variable_type_in"
     */
    public function testPropertyVariableTypeIn()
    {
    }

    /**
     * Test attribute "include_deleted"
     */
    public function testPropertyIncludeDeleted()
    {
    }

    /**
     * Test attribute "process_instance_id"
     */
    public function testPropertyProcessInstanceId()
    {
    }

    /**
     * Test attribute "process_instance_id_in"
     */
    public function testPropertyProcessInstanceIdIn()
    {
    }

    /**
     * Test attribute "process_definition_id"
     */
    public function testPropertyProcessDefinitionId()
    {
    }

    /**
     * Test attribute "process_definition_key"
     */
    public function testPropertyProcessDefinitionKey()
    {
    }

    /**
     * Test attribute "execution_id_in"
     */
    public function testPropertyExecutionIdIn()
    {
    }

    /**
     * Test attribute "case_instance_id"
     */
    public function testPropertyCaseInstanceId()
    {
    }

    /**
     * Test attribute "case_execution_id_in"
     */
    public function testPropertyCaseExecutionIdIn()
    {
    }

    /**
     * Test attribute "case_activity_id_in"
     */
    public function testPropertyCaseActivityIdIn()
    {
    }

    /**
     * Test attribute "task_id_in"
     */
    public function testPropertyTaskIdIn()
    {
    }

    /**
     * Test attribute "activity_instance_id_in"
     */
    public function testPropertyActivityInstanceIdIn()
    {
    }

    /**
     * Test attribute "tenant_id_in"
     */
    public function testPropertyTenantIdIn()
    {
    }

    /**
     * Test attribute "without_tenant_id"
     */
    public function testPropertyWithoutTenantId()
    {
    }

    /**
     * Test attribute "variable_name_in"
     */
    public function testPropertyVariableNameIn()
    {
    }

    /**
     * Test attribute "sorting"
     */
    public function testPropertySorting()
    {
    }
}
