<?php
/**
 * HistoricActivityInstanceQueryDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/nik54rus/camunda-open-api.git
 * Camunda Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the Camunda code generator program.
 * https://github.com/nik54rus/camunda-open-api
 * Please update the test case below to test the model.
 */

namespace Camunda\Client;

use PHPUnit\Framework\TestCase;

/**
 * HistoricActivityInstanceQueryDtoTest Class Doc Comment
 *
 * @category    Class
 * @description A historic activity instance query which defines a group of historic activity instances
 * @package     Camunda\Client
 * @author      Camunda Codegen team
 * @link        https://github.com/nik54rus/camunda-open-api
 */
class HistoricActivityInstanceQueryDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HistoricActivityInstanceQueryDto"
     */
    public function testHistoricActivityInstanceQueryDto()
    {
    }

    /**
     * Test attribute "activity_instance_id"
     */
    public function testPropertyActivityInstanceId()
    {
    }

    /**
     * Test attribute "process_instance_id"
     */
    public function testPropertyProcessInstanceId()
    {
    }

    /**
     * Test attribute "process_definition_id"
     */
    public function testPropertyProcessDefinitionId()
    {
    }

    /**
     * Test attribute "execution_id"
     */
    public function testPropertyExecutionId()
    {
    }

    /**
     * Test attribute "activity_id"
     */
    public function testPropertyActivityId()
    {
    }

    /**
     * Test attribute "activity_name"
     */
    public function testPropertyActivityName()
    {
    }

    /**
     * Test attribute "activity_type"
     */
    public function testPropertyActivityType()
    {
    }

    /**
     * Test attribute "task_assignee"
     */
    public function testPropertyTaskAssignee()
    {
    }

    /**
     * Test attribute "finished"
     */
    public function testPropertyFinished()
    {
    }

    /**
     * Test attribute "unfinished"
     */
    public function testPropertyUnfinished()
    {
    }

    /**
     * Test attribute "canceled"
     */
    public function testPropertyCanceled()
    {
    }

    /**
     * Test attribute "complete_scope"
     */
    public function testPropertyCompleteScope()
    {
    }

    /**
     * Test attribute "started_before"
     */
    public function testPropertyStartedBefore()
    {
    }

    /**
     * Test attribute "started_after"
     */
    public function testPropertyStartedAfter()
    {
    }

    /**
     * Test attribute "finished_before"
     */
    public function testPropertyFinishedBefore()
    {
    }

    /**
     * Test attribute "finished_after"
     */
    public function testPropertyFinishedAfter()
    {
    }

    /**
     * Test attribute "tenant_id_in"
     */
    public function testPropertyTenantIdIn()
    {
    }

    /**
     * Test attribute "without_tenant_id"
     */
    public function testPropertyWithoutTenantId()
    {
    }

    /**
     * Test attribute "sorting"
     */
    public function testPropertySorting()
    {
    }
}
