<?php
/**
 * HistoricTaskInstanceQueryDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/nik54rus/camunda-open-api.git
 * Camunda Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the Camunda code generator program.
 * https://github.com/nik54rus/camunda-open-api
 * Please update the test case below to test the model.
 */

namespace Camunda\Client;

use PHPUnit\Framework\TestCase;

/**
 * HistoricTaskInstanceQueryDtoTest Class Doc Comment
 *
 * @category    Class
 * @description A Historic Task instance query which defines a list of Historic Task instances
 * @package     Camunda\Client
 * @author      Camunda Codegen team
 * @link        https://github.com/nik54rus/camunda-open-api
 */
class HistoricTaskInstanceQueryDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "HistoricTaskInstanceQueryDto"
     */
    public function testHistoricTaskInstanceQueryDto()
    {
    }

    /**
     * Test attribute "task_id"
     */
    public function testPropertyTaskId()
    {
    }

    /**
     * Test attribute "task_parent_task_id"
     */
    public function testPropertyTaskParentTaskId()
    {
    }

    /**
     * Test attribute "process_instance_id"
     */
    public function testPropertyProcessInstanceId()
    {
    }

    /**
     * Test attribute "process_instance_business_key"
     */
    public function testPropertyProcessInstanceBusinessKey()
    {
    }

    /**
     * Test attribute "process_instance_business_key_in"
     */
    public function testPropertyProcessInstanceBusinessKeyIn()
    {
    }

    /**
     * Test attribute "process_instance_business_key_like"
     */
    public function testPropertyProcessInstanceBusinessKeyLike()
    {
    }

    /**
     * Test attribute "execution_id"
     */
    public function testPropertyExecutionId()
    {
    }

    /**
     * Test attribute "process_definition_id"
     */
    public function testPropertyProcessDefinitionId()
    {
    }

    /**
     * Test attribute "process_definition_key"
     */
    public function testPropertyProcessDefinitionKey()
    {
    }

    /**
     * Test attribute "process_definition_name"
     */
    public function testPropertyProcessDefinitionName()
    {
    }

    /**
     * Test attribute "case_instance_id"
     */
    public function testPropertyCaseInstanceId()
    {
    }

    /**
     * Test attribute "case_execution_id"
     */
    public function testPropertyCaseExecutionId()
    {
    }

    /**
     * Test attribute "case_definition_id"
     */
    public function testPropertyCaseDefinitionId()
    {
    }

    /**
     * Test attribute "case_definition_key"
     */
    public function testPropertyCaseDefinitionKey()
    {
    }

    /**
     * Test attribute "case_definition_name"
     */
    public function testPropertyCaseDefinitionName()
    {
    }

    /**
     * Test attribute "activity_instance_id_in"
     */
    public function testPropertyActivityInstanceIdIn()
    {
    }

    /**
     * Test attribute "task_name"
     */
    public function testPropertyTaskName()
    {
    }

    /**
     * Test attribute "task_name_like"
     */
    public function testPropertyTaskNameLike()
    {
    }

    /**
     * Test attribute "task_description"
     */
    public function testPropertyTaskDescription()
    {
    }

    /**
     * Test attribute "task_description_like"
     */
    public function testPropertyTaskDescriptionLike()
    {
    }

    /**
     * Test attribute "task_definition_key"
     */
    public function testPropertyTaskDefinitionKey()
    {
    }

    /**
     * Test attribute "task_definition_key_in"
     */
    public function testPropertyTaskDefinitionKeyIn()
    {
    }

    /**
     * Test attribute "task_delete_reason"
     */
    public function testPropertyTaskDeleteReason()
    {
    }

    /**
     * Test attribute "task_delete_reason_like"
     */
    public function testPropertyTaskDeleteReasonLike()
    {
    }

    /**
     * Test attribute "task_assignee"
     */
    public function testPropertyTaskAssignee()
    {
    }

    /**
     * Test attribute "task_assignee_like"
     */
    public function testPropertyTaskAssigneeLike()
    {
    }

    /**
     * Test attribute "task_owner"
     */
    public function testPropertyTaskOwner()
    {
    }

    /**
     * Test attribute "task_owner_like"
     */
    public function testPropertyTaskOwnerLike()
    {
    }

    /**
     * Test attribute "task_priority"
     */
    public function testPropertyTaskPriority()
    {
    }

    /**
     * Test attribute "assigned"
     */
    public function testPropertyAssigned()
    {
    }

    /**
     * Test attribute "unassigned"
     */
    public function testPropertyUnassigned()
    {
    }

    /**
     * Test attribute "finished"
     */
    public function testPropertyFinished()
    {
    }

    /**
     * Test attribute "unfinished"
     */
    public function testPropertyUnfinished()
    {
    }

    /**
     * Test attribute "process_finished"
     */
    public function testPropertyProcessFinished()
    {
    }

    /**
     * Test attribute "process_unfinished"
     */
    public function testPropertyProcessUnfinished()
    {
    }

    /**
     * Test attribute "task_due_date"
     */
    public function testPropertyTaskDueDate()
    {
    }

    /**
     * Test attribute "task_due_date_before"
     */
    public function testPropertyTaskDueDateBefore()
    {
    }

    /**
     * Test attribute "task_due_date_after"
     */
    public function testPropertyTaskDueDateAfter()
    {
    }

    /**
     * Test attribute "without_task_due_date"
     */
    public function testPropertyWithoutTaskDueDate()
    {
    }

    /**
     * Test attribute "task_follow_up_date"
     */
    public function testPropertyTaskFollowUpDate()
    {
    }

    /**
     * Test attribute "task_follow_up_date_before"
     */
    public function testPropertyTaskFollowUpDateBefore()
    {
    }

    /**
     * Test attribute "task_follow_up_date_after"
     */
    public function testPropertyTaskFollowUpDateAfter()
    {
    }

    /**
     * Test attribute "started_before"
     */
    public function testPropertyStartedBefore()
    {
    }

    /**
     * Test attribute "started_after"
     */
    public function testPropertyStartedAfter()
    {
    }

    /**
     * Test attribute "finished_before"
     */
    public function testPropertyFinishedBefore()
    {
    }

    /**
     * Test attribute "finished_after"
     */
    public function testPropertyFinishedAfter()
    {
    }

    /**
     * Test attribute "tenant_id_in"
     */
    public function testPropertyTenantIdIn()
    {
    }

    /**
     * Test attribute "without_tenant_id"
     */
    public function testPropertyWithoutTenantId()
    {
    }

    /**
     * Test attribute "task_variables"
     */
    public function testPropertyTaskVariables()
    {
    }

    /**
     * Test attribute "process_variables"
     */
    public function testPropertyProcessVariables()
    {
    }

    /**
     * Test attribute "variable_names_ignore_case"
     */
    public function testPropertyVariableNamesIgnoreCase()
    {
    }

    /**
     * Test attribute "variable_values_ignore_case"
     */
    public function testPropertyVariableValuesIgnoreCase()
    {
    }

    /**
     * Test attribute "task_involved_user"
     */
    public function testPropertyTaskInvolvedUser()
    {
    }

    /**
     * Test attribute "task_involved_group"
     */
    public function testPropertyTaskInvolvedGroup()
    {
    }

    /**
     * Test attribute "task_had_candidate_user"
     */
    public function testPropertyTaskHadCandidateUser()
    {
    }

    /**
     * Test attribute "task_had_candidate_group"
     */
    public function testPropertyTaskHadCandidateGroup()
    {
    }

    /**
     * Test attribute "with_candidate_groups"
     */
    public function testPropertyWithCandidateGroups()
    {
    }

    /**
     * Test attribute "without_candidate_groups"
     */
    public function testPropertyWithoutCandidateGroups()
    {
    }

    /**
     * Test attribute "or_queries"
     */
    public function testPropertyOrQueries()
    {
    }

    /**
     * Test attribute "sorting"
     */
    public function testPropertySorting()
    {
    }
}
