<?php
/**
 * ProblemDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/nik54rus/camunda-open-api.git
 * Camunda Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the Camunda code generator program.
 * https://github.com/nik54rus/camunda-open-api
 * Please update the test case below to test the model.
 */

namespace Camunda\Client;

use PHPUnit\Framework\TestCase;

/**
 * ProblemDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ProblemDto
 * @package     Camunda\Client
 * @author      Camunda Codegen team
 * @link        https://github.com/nik54rus/camunda-open-api
 */
class ProblemDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ProblemDto"
     */
    public function testProblemDto()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "line"
     */
    public function testPropertyLine()
    {
    }

    /**
     * Test attribute "column"
     */
    public function testPropertyColumn()
    {
    }

    /**
     * Test attribute "main_element_id"
     */
    public function testPropertyMainElementId()
    {
    }

    /**
     * Test attribute "element_ids"
     */
    public function testPropertyElementIds()
    {
    }
}
