<?php
/**
 * SortTaskQueryParametersDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/nik54rus/camunda-open-api.git
 * Camunda Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the Camunda code generator program.
 * https://github.com/nik54rus/camunda-open-api
 * Please update the test case below to test the model.
 */

namespace Camunda\Client;

use PHPUnit\Framework\TestCase;

/**
 * SortTaskQueryParametersDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Mandatory when &#x60;sortBy&#x60; is one of the following values: &#x60;processVariable&#x60;, &#x60;executionVariable&#x60;, &#x60;taskVariable&#x60;, &#x60;caseExecutionVariable&#x60; or &#x60;caseInstanceVariable&#x60;. Must be a JSON object with the properties &#x60;variable&#x60; and &#x60;type&#x60; where &#x60;variable&#x60; is a variable name and &#x60;type&#x60; is the name of a variable value type.
 * @package     Camunda\Client
 * @author      Camunda Codegen team
 * @link        https://github.com/nik54rus/camunda-open-api
 */
class SortTaskQueryParametersDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SortTaskQueryParametersDto"
     */
    public function testSortTaskQueryParametersDto()
    {
    }

    /**
     * Test attribute "variable"
     */
    public function testPropertyVariable()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }
}
