<?php
/**
 * ModificationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/nik54rus/camunda-open-api.git
 * Camunda Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the Camunda code generator program.
 * https://github.com/nik54rus/camunda-open-api
 * Please update the test case below to test the endpoint.
 */

namespace Camunda\Client;

use Camunda\Client\Configuration;
use Camunda\Client\ApiException;
use Camunda\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ModificationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */
class ModificationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for executeModification
     *
     * Execute Modification.
     *
     */
    public function testExecuteModification()
    {
    }

    /**
     * Test case for executeModificationAsync
     *
     * Execute Modification Async (Batch).
     *
     */
    public function testExecuteModificationAsync()
    {
    }
}
