<?php
/**
 * ProcessInstanceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProcessInstanceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProcessInstanceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for correlateMessageAsyncOperation
     *
     * Correlate Message Async (POST).
     *
     */
    public function testCorrelateMessageAsyncOperation()
    {
    }

    /**
     * Test case for deleteAsyncHistoricQueryBased
     *
     * Delete Async Historic Query Based (POST).
     *
     */
    public function testDeleteAsyncHistoricQueryBased()
    {
    }

    /**
     * Test case for deleteProcessInstance
     *
     * Delete.
     *
     */
    public function testDeleteProcessInstance()
    {
    }

    /**
     * Test case for deleteProcessInstanceVariable
     *
     * Delete Process Variable.
     *
     */
    public function testDeleteProcessInstanceVariable()
    {
    }

    /**
     * Test case for deleteProcessInstancesAsyncOperation
     *
     * Delete Async (POST).
     *
     */
    public function testDeleteProcessInstancesAsyncOperation()
    {
    }

    /**
     * Test case for getActivityInstanceTree
     *
     * Get Activity Instance.
     *
     */
    public function testGetActivityInstanceTree()
    {
    }

    /**
     * Test case for getProcessInstance
     *
     * Get Process Instance.
     *
     */
    public function testGetProcessInstance()
    {
    }

    /**
     * Test case for getProcessInstanceComments
     *
     * Get Process Instance Comments.
     *
     */
    public function testGetProcessInstanceComments()
    {
    }

    /**
     * Test case for getProcessInstanceVariable
     *
     * Get Process Variable.
     *
     */
    public function testGetProcessInstanceVariable()
    {
    }

    /**
     * Test case for getProcessInstanceVariableBinary
     *
     * Get Process Variable (Binary).
     *
     */
    public function testGetProcessInstanceVariableBinary()
    {
    }

    /**
     * Test case for getProcessInstanceVariables
     *
     * Get Process Variables.
     *
     */
    public function testGetProcessInstanceVariables()
    {
    }

    /**
     * Test case for getProcessInstances
     *
     * Get List.
     *
     */
    public function testGetProcessInstances()
    {
    }

    /**
     * Test case for getProcessInstancesCount
     *
     * Get List Count.
     *
     */
    public function testGetProcessInstancesCount()
    {
    }

    /**
     * Test case for modifyProcessInstance
     *
     * Modify Process Instance Execution State.
     *
     */
    public function testModifyProcessInstance()
    {
    }

    /**
     * Test case for modifyProcessInstanceAsyncOperation
     *
     * Modify Process Instance Execution State Async.
     *
     */
    public function testModifyProcessInstanceAsyncOperation()
    {
    }

    /**
     * Test case for modifyProcessInstanceVariables
     *
     * Update/Delete Process Variables.
     *
     */
    public function testModifyProcessInstanceVariables()
    {
    }

    /**
     * Test case for queryProcessInstances
     *
     * Get List (POST).
     *
     */
    public function testQueryProcessInstances()
    {
    }

    /**
     * Test case for queryProcessInstancesCount
     *
     * Get List Count (POST).
     *
     */
    public function testQueryProcessInstancesCount()
    {
    }

    /**
     * Test case for setProcessInstanceVariable
     *
     * Update Process Variable.
     *
     */
    public function testSetProcessInstanceVariable()
    {
    }

    /**
     * Test case for setProcessInstanceVariableBinary
     *
     * Update Process Variable (Binary).
     *
     */
    public function testSetProcessInstanceVariableBinaryForm()
    {
    }

    /**
     * Test case for setRetriesByProcess
     *
     * Set Job Retries Async (POST).
     *
     */
    public function testSetRetriesByProcess()
    {
    }

    /**
     * Test case for setRetriesByProcessHistoricQueryBased
     *
     * Set Job Retries Async Historic Query Based (POST).
     *
     */
    public function testSetRetriesByProcessHistoricQueryBased()
    {
    }

    /**
     * Test case for setVariablesAsyncOperation
     *
     * Set Variables Async (POST).
     *
     */
    public function testSetVariablesAsyncOperation()
    {
    }

    /**
     * Test case for updateSuspensionState
     *
     * Activate/Suspend In Group.
     *
     */
    public function testUpdateSuspensionState()
    {
    }

    /**
     * Test case for updateSuspensionStateAsyncOperation
     *
     * Activate/Suspend In Batch.
     *
     */
    public function testUpdateSuspensionStateAsyncOperation()
    {
    }

    /**
     * Test case for updateSuspensionStateById
     *
     * Activate/Suspend Process Instance By Id.
     *
     */
    public function testUpdateSuspensionStateById()
    {
    }
}
