<?php
/**
 * TaskVariableApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TaskVariableApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TaskVariableApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteTaskVariable
     *
     * Delete Task Variable.
     *
     */
    public function testDeleteTaskVariable()
    {
    }

    /**
     * Test case for getTaskVariable
     *
     * Get Task Variable.
     *
     */
    public function testGetTaskVariable()
    {
    }

    /**
     * Test case for getTaskVariableBinary
     *
     * Get Task Variable (Binary).
     *
     */
    public function testGetTaskVariableBinary()
    {
    }

    /**
     * Test case for getTaskVariables
     *
     * Get Task Variables.
     *
     */
    public function testGetTaskVariables()
    {
    }

    /**
     * Test case for modifyTaskVariables
     *
     * Update/Delete Task Variables.
     *
     */
    public function testModifyTaskVariables()
    {
    }

    /**
     * Test case for putTaskVariable
     *
     * Update Task Variable.
     *
     */
    public function testPutTaskVariable()
    {
    }

    /**
     * Test case for setBinaryTaskVariable
     *
     * Update Task Variable (Binary).
     *
     */
    public function testSetBinaryTaskVariableForm()
    {
    }
}
