<?php
/**
 * UserApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */

/**
 * Camunda Platform REST API
 *
 * OpenApi Spec for Camunda Platform REST API.
 *
 * OpenAPI spec version: 7.21.1-ee
 * 
 * Generated by: https://github.com/nik54rus/camunda-open-api.git
 * Camunda Codegen version: 3.0.56
 */
/**
 * NOTE: This class is auto generated by the Camunda code generator program.
 * https://github.com/nik54rus/camunda-open-api
 * Please update the test case below to test the endpoint.
 */

namespace Camunda\Client;

use Camunda\Client\Configuration;
use Camunda\Client\ApiException;
use Camunda\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Camunda\Client
 * @author   Nik54rus
 * @link     https://github.com/nik54rus/camunda-open-api
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for availableOperations
     *
     * Options.
     *
     */
    public function testAvailableOperations()
    {
    }

    /**
     * Test case for availableUserOperations
     *
     * Options.
     *
     */
    public function testAvailableUserOperations()
    {
    }

    /**
     * Test case for createUser
     *
     * Create.
     *
     */
    public function testCreateUser()
    {
    }

    /**
     * Test case for deleteUser
     *
     * Delete.
     *
     */
    public function testDeleteUser()
    {
    }

    /**
     * Test case for getUserCount
     *
     * Get List Count.
     *
     */
    public function testGetUserCount()
    {
    }

    /**
     * Test case for getUserProfile
     *
     * Get Profile.
     *
     */
    public function testGetUserProfile()
    {
    }

    /**
     * Test case for getUsers
     *
     * Get List.
     *
     */
    public function testGetUsers()
    {
    }

    /**
     * Test case for unlockUser
     *
     * Unlock User.
     *
     */
    public function testUnlockUser()
    {
    }

    /**
     * Test case for updateCredentials
     *
     * Update Credentials.
     *
     */
    public function testUpdateCredentials()
    {
    }

    /**
     * Test case for updateProfile
     *
     * Update User Profile.
     *
     */
    public function testUpdateProfile()
    {
    }
}
